### ISSUE TITLE
uBlock-Edge - Update Filters Infinity Loop Loading Circles - Clear Browsing Data - Bing Ads

### ISSUE THREAD

**Issue by ghost** [nikrolls/uBlock-Edge#72] opened 2017-04-15 17:51 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When updating filters, UI doesn't always update to show they've finished loading.

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen

![capture ublock second stage update freeze](https://cloud.githubusercontent.com/assets/17460623/25065475/faac96ec-2210-11e7-8e2c-c65b0a774b02.PNG)

### Steps for anyone to reproduce the issue
1. Manually update the 3rd-party filters list
2. Watch the spinners start spinning as filters are loading
3. Notice that they don't appear to finish loading
4. Refresh the page after a short while and notice that they have actually finished loading but the page never updated

### Your settings

- OS/version: Microsoft Windows 10 1703 15063.138 
- Browser/version: Microsoft Edge 40.15063.0.0
- uBlock Origin version: uBlock 1.12.0

##### Your filter lists
Default 

##### Your custom filters (if any) 
N/A

**Comment by nikrolls** [comment] 2017-04-16 03:56
Hi @DeathRowRecords, you appear to be reporting three different things here. Can you please split it to three different reports (check existing issues to see if any of them are already reported) and please add as much detail as possible to the template.

**Comment by ghajini** [comment] 2017-04-16 05:13
He wants to say.....while updating 3rd party filters, loading loop next to that filter doesn't end and it just keeps on loading.....its just a bug in ublock edge/css animation introduced by gorhill upstream works in chrome.....while its just that loading loop that never ends,
but in end 3rd party filter is already updated in time comparable to chrome version...

**Comment by DeathRowRecords** [comment] 2017-04-16 11:33
Yes Hi Hello @nikrolls if I'm gonna do dat and separate those 3 issues I'm convinced that you be so certain that it's a SPAM! But my motion to set aside Judgment. Blue Eyed people are deemed least trustworthy, but are GOOD and strategic thinkers. So they might be able to con others easily ( But Not Me ) I Refuse and Fail To Obey! So help me God, I'm one with the force the force is with me! Figure that out.

Hi @ghajini  u r a Cool Guy ( I appreciate that )  4 ur Dominant Intuition.

**Comment by edrmrk** [comment] 2017-04-17 08:57
I'm having the infinite loop bug ad yeah after some minutes the filters are updated but the problem is that for me they roll back to the outdated version and needs the updates again (after 2 or 3 hours)

**Comment by nikrolls** [comment] 2017-04-17 20:17
I'm noticing this as well. They do update but they UI doesn't reflect this until you refresh it. I'll investigate. I need to update this ticket though as it's very unclear and it should only refer to one issue.

**Comment by nikrolls** [comment] 2017-04-17 20:24
Regarding the note about 'spam' and 'ego', I have noticed issues being created here that are vaguely related to uBlock but are also full of spam links and basically unintelligible. I have been reporting them as spam. The user who created them then started emailing me personally with emails full of the same behaviour. It appears that this may be the same person again but at least in this case they are not submitting spam.

**Comment by nikrolls** [comment] 2017-04-17 20:26
The issue with clearing the browser cache is may be uBlock related but will not be a uBlock issue. It previously used IndexedDB which is cleared when you clear the browser cache. Since public launch, for users on the Creators Update, uBlock uses the unlimited local storage provided for extensions instead. That may actually help the infinite loading issue as well (considering it's the 3rd-party lists whose storage was switched) as I can't reproduce this issue on uBlock 1.12.1.

**Comment by DeathRowRecords** [comment] 2017-04-18 09:06
Hi @nikrolls  Clearing Browsing Data "Some data couldn't be clear. Please try again" it appears that filters need to load/download/update first ( 3-4 min ) then you can see "All Clean" with the success on your face. 
Edit: I'm Obligated to reply on calling me "unintelligible" and scrutinize I can often appear to retain a child like prone where even in adulthood I look at the world with a vividness and sense of wonder that is usually lost to other as they grow up but however childlike I my seem "ME" should not be mistaken for simpletons or immature individual in truth I'm reflective and intelligent individual. I Bore easily and my not bode well in long relationship, my sense of adventure and passion for risk taking may play a part in my tendency  be unengaged hen not stimulated ( your reply to me ) I'm very sharp witty d unpredictable, I'm not afraid to avoid conflict so I learn from early age how be sharp and conning when conflict occurs. 

Have a Nice Day Nik

**Comment by dhigh88** [comment] 2017-05-09 00:11
@nikrolls Hello, is there any latest on this issue please? I'm facing the same circle loops when filters update but they claim to be updated when the page is refreshed. I don't think that's the case because I get the most unnecessary pop ups such as "system error warnings" on certain sites I visit; meanwhile on Firefox or Chrome they get automatically blocked. It makes me feel like Edge' ublock version doesn't update to the latest filters like Firefox or Chrome.

**Comment by DeathRowRecords** [comment] 2017-06-09 16:36
Top o' the mornin' to ya" @nikrolls sir, I don't always leave my friends behind but when i do It's because my friends don't dance and if they don't dance, well then they're no friends of mine. I think we can wrap this up and close this bug report of mine. Maintenance? Sir, I have had enough of your shinanigans, so i bid you good day! I said good day to ya! sir! :)) As always looking forward to follow upcoming progress.

**Comment by nikrolls** [comment] 2018-02-04 04:36
Closing because the bug described is no longer an issue.

**Closed by nikrolls** 2018-02-04 04:36 UTC
