### ISSUE TITLE
Unable to browse tomshardware

### ISSUE THREAD

**Issue by laxman20** [nikrolls/uBlock-Edge#51] opened 2017-01-07 17:01 UTC
### Describe the issue

Trying to enter the website from a new tab redirects back to new tab.  Trying to enter through a Google search result results in a prompt to save a file

### One or more specific URLs where the issue occurs

www.tomshardware.com
www.tomsguide.com

### Steps for anyone to reproduce the issue

1. Open Edge
2. enter "www.tomshardware.com"

### Your settings

- Browser/version: 38.14393.0.0
- uBlock Origin version: 1.10.2

##### Your filter lists

Default lists

**Comment by gorhill** [comment] 2017-01-07 17:49
Duplicate of #45.

**Comment by nikrolls** [comment] 2017-01-11 01:18
Agreed. There is a fix on the way from Microsoft.

**Closed by nikrolls** 2017-01-11 01:18 UTC
