### ISSUE TITLE
uBlock / Easylist causes sites to download .htm file

### ISSUE THREAD

**Issue by jhoff80** [nikrolls/uBlock-Edge#61] opened 2017-03-06 05:10 UTC
### Describe the issue
When Easylist is enabled, going to certain domains (xda, pcgamer, and others) opens up the download bar - What would you like to do with <random letters>.htm.  This issue does not occur in Chrome or Firefox with Easylist enabled when visiting the same sites.

### One or more specific URLs where the issue occurs

www.xda-developers.com
www.pcgamer.com

### Steps for anyone to reproduce the issue

For me this happens every single time as long as I enable uBlock Origin, make sure Easylist is enabled, and go to the aforementioned domains.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version:  Edge 40.15048.0.0 / EdgeHTML 15.15048
- uBlock Origin version: uBlock Origin v1.11.2

##### Your filter lists

Default filter lists - narrowed down the issue to Easylist

**Comment by Frelnik** [comment] 2017-03-07 01:30
I have the same experience. The temporary solution suggested here [https://github.com/nikrolls/uBlock-Edge/issues/45](https://github.com/nikrolls/uBlock-Edge/issues/45) to add _@@$websocket_ to the filter list does not work after the update to v1.11.2. The filter did work prior to the update.

**Comment by gorhill** [comment] 2017-03-07 01:32
Add `@@|blob:`. 1.11.2 supports foiling web workers through `|blob:` filter, so you will have to prevent CSP injection by cancelling `|blob:` filters.

**Comment by nikrolls** [comment] 2017-03-07 01:36
Yep, duplicate of #45. Thanks @gorhill for the workaround. This is pending a fix in Edge, and I've been told it's imminent. It's the last issue to be fixed before making the extension public.

**Closed** 2017-03-07 01:38 UTC
