### ISSUE TITLE
Updating third-party filters is horrendously slow on Edge for build 15007

### ISSUE THREAD

**Issue by vemacs** [nikrolls/uBlock-Edge#54] opened 2017-01-16 15:22 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

The progressbar when updating third-party filters hangs about halfway, around the first pull from the web when trying to update filter lists in Edge on Windows 10 15007.

### One or more specific URLs where the issue occurs

ms-browser-extension://EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62/dashboard.html

### Screenshot in which the issue can be seen

Not sure if this is a visual issue, but:

![](https://i.imgur.com/XS4FssA.png)

### Steps for anyone to reproduce the issue

1. Open settings
2. Click third-party filter lists
3. Click update
4. Wait

### Your settings

All default settings

- Browser/version: Microsoft Edge 15007
- uBlock Origin version: 1.10.2

##### Your filter lists

Default filter lists + Anti-Adblock Killer

**Comment by gorhill** [comment] 2017-01-16 15:35
> hangs about halfway

There is a timeout of 30 seconds if a server does not respond to a request when fetching a filter list. Did you have to wait more than 30 seconds?

**Comment by vemacs** [comment] 2017-01-16 15:36
I waited about 5 minutes.

**Comment by japborst** [comment] 2017-01-16 15:41
This used to happen pre- #21. Shouldn't happen on 1.10.2, but perhaps the latest fast build introduces some new issues or is buggy with its communication. My guess it's the same type of issue. I'm still on the slow ring (14986), so unfortunately cannot test this... When refreshing, do the lists still show that an update is available?

**Comment by vemacs** [comment] 2017-01-16 15:42
Yes, the orange update available indicator does ont go away.

**Comment by nikrolls** [comment] 2017-01-16 19:46
Yes, I've had this happen to me once (out of many times) and mentioned by someone else. It's a tricky one to reproduce.

**Comment by vemacs** [comment] 2017-01-16 19:46
This seems to happen 100% of the time on 15007

**Comment by kevin12314** [comment] 2017-01-19 15:31
I find that in build 15007, "Enabled XMLHttpRequests  over Fetch" is by default in about:flags.
With this enabled , I will get error to update user script or import user script with URL in Tempmonkey , and update third-party filters in ublock Origin get vary slow .

**Comment by nikrolls** [comment] 2017-01-19 18:20
Thanks @kevin12314, that gives me somewhere to look. I know the Edge team are doing a lot of work in that area and I'll let them know.

**Comment by TRoskop** [comment] 2017-02-20 15:37
Tested this on the most-recent Windows10 build (15025).
I cannot confirm this bug. As I tested it, it updated all the lists in less than 2 minutes.

**Comment by vemacs** [comment] 2017-02-20 15:40
1. 15025 is not the latest windows 10 build
2. 2 minutes is still an order of magnitude longer than what ublock takes on other browsers

**Comment by TRoskop** [comment] 2017-02-20 15:48
@vemacs : Build 15025 is the most-recent *stable* build. Of course, there is the newer build 15031, but it is marked as unstable/fast-ring.
And as Microsoft recommends, devs should focus on stable versions. 

I tested the extension for Edge and the extension for Chrome.
Edge needed 00:52 seconds to update all filters, Chrome needed 00:36 seconds.

**Comment by gorhill** [comment] 2017-02-20 15:56
> Edge needed 00:52 seconds to update all filters, Chrome needed 00:36 seconds

For Chrome, was this uBO 1.11.0? If so, that part of the code has been re-factored and I have shortened the delay between each fetch, from 5 seconds to 2 seconds. Also, with 1.11.0, it's possible to [configure the delay between each fetch](https://github.com/gorhill/uBlock/wiki/Advanced-settings#manualupdateassetfetchperiod). The reason for the delay is to be gentle on remote servers, and to be slow-connection friendly.

**Comment by vemacs** [comment] 2017-02-20 15:57
You're right that this bug can be closed then, as the updating process doesn't outright hang anymore.

**Comment by TRoskop** [comment] 2017-02-20 16:01
![image](https://cloud.githubusercontent.com/assets/13079737/23132504/1c1acbda-f78e-11e6-90db-1f041b197238.png)
![image](https://cloud.githubusercontent.com/assets/13079737/23132530/2a1e08dc-f78e-11e6-99f3-f1c9fd04dbbf.png)

@gorhill 
These are the versions on my machine.
Both are running with default configs, no changes applied.

**Comment by vemacs** [comment] 2017-03-11 19:21
This is actually happening again with the latest store build and Win10 15055.

**Comment by gorhill** [comment] 2017-03-11 19:42
I looked into the code to be sure, and the only way I can explain what you observe is if the "Update now" button did not actually send the order to update the filters to the main process. This would mean that the filter lists were actually updated by the auto-updater, which causes filter lists to be slowly updated in the background (auto-updater will update a filter list if needed at most once every two minutes).

@nikrolls That would be the first thing to look at, whether it can happen the "Update now" button does not result in [this handler](https://github.com/gorhill/uBlock/blob/cbca48307c50d4e243462c4c86af03453bbdf766/src/js/messaging.js#L123) to be called.

**Comment by nikrolls** [comment] 2018-02-06 18:48
@vemacs, are you still experiencing this issue with the latest Windows and uBlock Origin releases?

**Comment by nikrolls** [comment] 2018-02-14 21:12
Closing this due to a lack of activity and being unable to reproduce the issue any longer.

**Closed by nikrolls** 2018-02-14 21:12 UTC
Labels: needs investigation
