### ISSUE TITLE
Frequent broken layout opening pages in new tabs

### ISSUE THREAD

**Issue by raxbe** [nikrolls/uBlock-Edge#40] opened 2016-12-14 16:49 UTC
### Describe the issue
Opening article pages in new tabs on former Gawker sites like Kotaku, Gizmodo, etc breaks the layout/format of the related articles and comment section. Refreshing the page at that point typically fixes the problem. This happens most of the time but oddly not always.

### Screenshot in which the issue can be seen
Broken:
![1](https://cloud.githubusercontent.com/assets/24570254/21189138/f2aa6d46-c21d-11e6-8e62-97ddc0ecc6f5.jpg)
Normal:
![2](https://cloud.githubusercontent.com/assets/24570254/21190256/7d673920-c221-11e6-9b42-c4238e2210a7.jpg)

### Steps for anyone to reproduce the issue

1. Go to gizmodo.com
2. Right-click article title and select open in a new tab

### Your settings

- Browser/version: Microsoft Edge 38.14393.0.0
                              Microsoft EdgeHTML 14.14393
- uBlock Origin version: 1.10.1.0

##### Your filter lists

Default filter lists + NLD minus Peter Lowe's Ad list

##### Your custom filters (if any)

None

**Comment by nikrolls** [comment] 2016-12-14 19:56
Thanks @raxbe for the report, I'll look into it!

**Comment by nikrolls** [comment] 2016-12-19 07:04
I'm unable to reproduce this in 1.10.1 or 1.10.2 using 39.14986.1000.0 (Fast Ring). I'll take a look at it in public release and update.

**Comment by nikrolls** [comment] 2018-02-06 20:05
I'm closing this now as there have been no recent reports of the issue. Feel free to open it again if there is further information.

**Closed by nikrolls** 2018-02-06 20:05 UTC
Labels: needs investigation
