### ISSUE TITLE
Windows 10 (Creators Update) + Edge + uBlock Origin = Issues

### ISSUE THREAD

**Issue by l33twannabe** [nikrolls/uBlock-Edge#66] opened 2017-04-06 10:18 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

After updating to Creators Update, I decided to switch to Microsoft Edge and one of the first things I did was to get ublock origin. Unfortunately, there seems to be some issue with it working with Edge, at least on the newest update (creators update). I noticed that, after some time, sites don't load. I get "waiting for response from ..." information and nothing happens. I'm pretty sure it's ublock's fault because if the extension is turned off, everything works as it should. One more thing I noticed is that when I get "waiting for response from ..." information, all I need to do is click on ublock's icon next to the address bar to make the site load properly.

### One or more specific URLs where the issue occurs

It actually happens randomly, but when it comes to GitHub - it always happens.

https://github.com/

### Screenshot in which the issue can be seen

http://imgur.com/a/sfxXu

### Steps for anyone to reproduce the issue

1. Go to https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4?tduid=(6870372bcce6e460ca2a744461790425)(259740)(2542549)(UUwpUdUnU45362)()
2. Install the extension.
3. Open Microsoft Edge and go to https://github.com/

### Your settings

- Browser/version: Microsoft Edge 40.15063.0.0
- uBlock Origin version: 1.11.2

##### Your filter lists

Default filter lists

**Comment by debsuvra** [comment] 2017-04-06 11:25
I'm also using the same versions of Edge and uBlock Origin on Windows 10 Creators Update. I couldn't reproduce your issue.

**Comment by l33twannabe** [comment] 2017-04-06 15:30
After uninstalling/installing ublock again, everything seems to be working fine (at least for now). If anything comes up, I'll be back to report.

**Comment by l33twannabe** [comment] 2017-04-06 17:45
It was fine for about 2-3 hours, but after restarting my pc it started happening again. As soon as I click on the ublock's icon (no need to turn it off/on, just a simple click), sites start to load. No such issues with ublock turned off completely. Looks like I have to go back to Chrome until this is fixed.

**Comment by parkerlamb** [comment] 2017-04-06 21:41
I'm having the same issue as @l33twannabe, I have the same Edge/uBlock versions as well. I get this most commonly when the computer has resumed from sleep and Edge has been left open. Closing/reopening Edge fixes the problem temporarily, as does clicking the uBlock icon as suggested above. Can't provide a better repro than that, sorry.

**Comment by kurtglover33** [comment] 2017-04-08 04:53
I'm having the same issue as well, but I think Edge is the culprit here, as I've experienced the exact same problem with Adguard.

**Comment by l33twannabe** [comment] 2017-04-13 16:54
There's a new version (11.12.0). I'm testing now, but can anyone confirm the issue has been fixed ?

**Comment by parkerlamb** [comment] 2017-04-13 17:34
I haven't had this issue since KB4015583, I think it may have fixed this problem (and that it was Edge's fault).

**Comment by nikrolls** [comment] 2017-04-16 04:00
There is currently an issue with Edge where resuming from sleep will cause this exact issue with extensions. I've been told a fix is incoming.

**Comment by nikrolls** [comment] 2018-02-06 20:18
I'm closing this now as there have been no recent reports of the issue and the issue has been fixed in Edge. Feel free to open it again if there is further information.

**Closed by nikrolls** 2018-02-06 20:18 UTC
Labels: browser bug
