### ISSUE TITLE
Inline HTML5 video ads on youtube are not blocked and still show up

### ISSUE THREAD

**Issue by coolstar** [nikrolls/uBlock-Edge#41] opened 2016-12-14 18:55 UTC
### Describe the issue

Inline HTML5 video ads on youtube are not blocked and still show up.

Note: Video ads are blocked and don't show up with uBlock Origin in Chrome

https://www.youtube.com/watch?v=ENiAiSzVuVk

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/1431548/21196176/939aa7c6-c1eb-11e6-92b0-494621cf266c.png)

### Steps for anyone to reproduce the issue

1. Open Videos on YouTube

### Your settings

Default Settings

- Browser/version: Microsoft Edge 38.14393.0.0
- uBlock Origin version: 1.10.1

##### Your filter lists

Default Filter lists

**Comment by nikrolls** [comment] 2016-12-14 19:56
Hi @coolstar, thanks for the report. Can you please confirm that you've ensured your third-party lists are up-to-date? You'll need to go into uBlock options -> 3rd party filters -> Update now, and then check to see if you still get ads.

The reason is I think these may not be updating on install, which would be a different issue than it not being able to block HTML5 ads.

**Comment by japborst** [comment] 2016-12-15 09:08
@nikrolls I can confirm that no list is updated upon install. I'm not sure what the desired behaviour is?

**Comment by gorhill** [comment] 2016-12-15 14:07
Lists are updated when needed a couple of minutes after install. Each list is updated one by one with a good interval in between. Once all lists have been updated, all filters are reloaded. This is all done transparently.

**Comment by coolstar** [comment] 2016-12-18 08:32
@nikrolls the issue seems to happen at random, and seems to actually be a bigger issue. Sometimes, at random uBlock Origin stops blocking ads on all webpages in Edge... completely closing and restarting Edge seems to resolve it temporarily and the problem sometimes re-exhibits itself later

**Comment by gorhill** [comment] 2016-12-18 14:02
> Sometimes, at random uBlock Origin stops blocking ads on all webpages in Edge... completely closing and restarting Edge seems to resolve it temporarily and the problem sometimes re-exhibits itself later

Sounds like the symptom one would get if an exception was thrown somewhere in uBO's code, leaving it in a bad state. Is there such a thing as a dev console for extensions in Edge? If so, looking at errors in there could help.

**Comment by japborst** [comment] 2016-12-18 16:12
@gorhill yes, you can debug the extension through the dev console similar to Chrome. The hard part is that this has never occurred to me before and cannot produce the issue, so that makes it hard to debug.

**Comment by nikrolls** [comment] 2016-12-18 17:40
In 1.10.2 I fixed an issue with a couple of lists not loading the pre-packaged version. I'll take a look at whether they're updating automatically, with @gorhill's description in mind.

As @japborst says, there is a dev console but naturally one of us just needs to be able to reproduce the issue first.

**Comment by nikrolls** [comment] 2016-12-19 06:47
I'm unable to intentionally reproduce this, but I'll leave it open for now as it seems to be intermittent.

**Comment by Marocco2** [comment] 2016-12-20 22:26
I have 2 devices, my PC and the Surface Pro 3. Only the SP3 has this issue (last fast ring build available)

**Comment by ZenMasta** [comment] 2016-12-24 07:39
I have a surface pro 3 on and a desktop pc both on insider fast rings. I experience ads on youtube still as well. Infact I also got ads using adblock and adblock plus on microsoft edge too. If there was an easy way for me to submit a debug I'd gladly do it. Maybe there could be an option built into the extension where it would monitor the activity and then send a report back I wouldn't mind opting into that.

What's interesting to me is I have no problems with adblock/plus or adblock origin on chrome/vivaldi. It almost makes me wonder if Microsoft has a deal with youtube to prevent adblockers from blocking all ads on youtube. 

Not every video has ads, and not every video that displays an ad will display an ad everytime. But when you get an ad that's 2 minutes and no skip button, I'm glad I can open that video in tubecast pro via favorite bar shortcut cause otherwise I'd just not watch the video.

**Comment by japborst** [comment] 2016-12-24 11:51
Hah that'd be something, Microsoft having a deal with YouTube - they are a little conspicuous with ads on Bing, though. But on my SP3 I never have ads on YouTube so I know it's definitely possible. I assume filters are up to date? Can you check and do a manual update? Also, make sure you are using the HTML5 version of YouTube. You can check this here https://www.youtube.com/html5

**Comment by ghajini** [comment] 2017-03-26 20:26
i see no ads on youtube...i used html5 version of youtube or tried disabling flash and then use youtube...can't reproduce

**Comment by nikrolls** [comment] 2017-03-27 09:47
Thanks everyone for your feedback. It seems the experience is a little inconsistent. I'd be interested to see how this goes once the Creators Update comes out and this extension goes public.

**Comment by nikrolls** [comment] 2018-02-06 18:44
I'm closing this now as there have been no recent reports of the issue. Feel free to open it again if there is further information.

**Closed by nikrolls** 2018-02-06 18:44 UTC
Labels: needs investigation
