### ISSUE TITLE
ui bug possibly

### ISSUE THREAD

**Issue by ghajini** [nikrolls/uBlock-Edge#70] opened 2017-04-14 07:51 UTC
@nikrolls & @gorhill

### Describe the issue
this is ui bug og ublock edge...

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### video in which the issue can be seen

`https://www.dropbox.com/s/t2rlekz9nyrq5ww/2017-04-14_12-53-49.mp4?dl=0`

### Steps for anyone to reproduce the issue

1. go to any site like youtube.com
2. click on ublock edge icon ...
3. you will notice right half of ublock popup showing logger is cut, ass long as you move curser to left , ublock displays full popup of logger.....

4. i shared video,hope it will help you....

### Your settings

default settings

- OS/version: windows 10 build 15063.138, version 1703
- Browser/version: Microsoft Edge 40.15063.0.0
- uBlock Origin : 1.12

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

notes : 
this bug is not present upstream chrome version.....

**Comment by DesertBear** [comment] 2017-04-14 19:38
I'm also experiencing this issue.

- Sometimes the window doesn't open when clicking on the uBlock Origin icon, until navigating away from the current page and then back again.

- Sometimes the standard window is cut-off at the bottom until mouse-over.

- Sometimes the advanced window doesn't populate properly until mouse-over top 'Open Dashboard' menu bar.

**Screenshot:**
![002](https://cloud.githubusercontent.com/assets/27423064/25053890/09bbe6f2-2152-11e7-9eb8-1806ebf7d3c1.jpg)

**Comment by nikrolls** [comment] 2017-04-16 03:56
Thanks! I'll check this out.

**Comment by NetSoerfer** [comment] 2017-05-20 06:13
This is actually a pretty nasty issue when using Edge on a tablet, as without a mouse there is no way to fully expand the uBO UI with touch.

**Comment by stkb** [comment] 2017-07-25 17:32
Has this got worse for anyone else since the latest version since the latest version (1.13.8)? For me the window never opens up fully, and mouseover no longer works. The extension is basically unusable for me now :(

<img width="147" alt="ublock" src="https://user-images.githubusercontent.com/6125444/28585224-e8624050-716f-11e7-8364-363af3ed708e.png">

I noticed the little cog icon for the settings has now been moved from the title bar, so that may have something to do with mouseover no longer working.

I'll try digging into it, though @nikrolls do you know whether this is a bug in Edge?

**Comment by stkb** [comment] 2017-07-26 09:23
Have found that, while the popup almost never opens fully the first time for me, if I keep hitting the toolbar button to open and close it, eventually it will open at the correct size.

Seems to be because the popup's content is set dynamically in `renderPopup` (the `advancedUser` class is added to the `body` if required) and Edge doesn't always resize the popup width to accommodate the content.

I don't know if there's a way to force Edge to re-calculate the width of the popup. I've tried re-setting the width of the html and body elements after that code but it doesn't work reliably. Only by hardcoding the pixel width of the html element into the CSS file does it always open at the correct width every time.

**Comment by NetSoerfer** [comment] 2017-07-29 08:46
@stkb, it's the same for me, I can't get the Dashboard to open at all anymore.
@nikrolls, anything we can do to help? Have you been able to reproduce this?

**Comment by bdennir** [comment] 2017-09-17 21:33
Not a fix, but found a procedural workaround for that maybe help someone. Using Current Branch Windows 10 release — when clicking either the "requests blocked" line or the "domains connected" line, the popup toggles to the desired context & expands the little popup window. If the click is repeated, it shrinks the popup to an unexpanded state. Next try in other browsing, the popup opens unexpanded & can be expanded by clicking either line to enter that context without the concurrency problem of the window size. So far.

**Comment by nikrolls** [comment] 2018-02-06 20:19
This is now being tracked in #95 and fixed in #103.

**Closed by nikrolls** 2018-02-06 20:19 UTC
