### ISSUE TITLE
uBlock origin causes Edge tab crashing when clicking external links in Gmail

### ISSUE THREAD

**Issue by xyjprc** [nikrolls/uBlock-Edge#2] opened 2016-08-03 16:10 UTC
### Describe the issue

uBlock origin causes Edge tab crashing when clicking external links in Gmail.
### One or more specific URLs where the issue occurs

http://mail.google.com
### Steps for anyone to reproduce the issue
1. Enable uBlock origin in Edge
2. Open Gmail in Edge
3. Click any external link in a mail (such as "unsubscribe")
4. A new tab opens but not redirecting to the designated link; showing a blank tab
5. Meanwhile the original Gmail tab crashes and automatically reload.
6. Can repeat and it will reproduce.
7. Disable uBlock origin in Edge
8. The issue no longer exists.
### Your settings
- Browser/version: 38.14393.0.0
- uBlock Origin version: 1.7.7
##### Your filter lists

Default filter lists 
##### Your custom filters (if any)

None

**Comment by emannxx** [comment] 2016-08-08 12:36
A suggestion: this new extension-converter app from Microsoft might help porting uBlock. 
http://www.winbeta.org/news/microsoft-releases-edge-extension-toolkit-windows-10-helps-devs-port-extensions-chrome

**Comment by nikrolls** [comment] 2016-08-09 00:50
Issue confirmed in latest release. Doesn't happen in Chrome. Still persists even if you turn uBlock off for that page (only resolves itself if you turn uBlock off at the browser level).

**Comment by nikrolls** [comment] 2016-08-09 00:52
@emannxx: Regarding the converter app, it looks very useful but as far as I know only does what I had already done in the first iteration of this port. Most of the remaining issues are to do with Edge limitations/bugs combined with the unique requirements of this extension.

I do still plan to run the Chrome build through it and pick up anything I may have missed, however.

**Comment by japborst** [comment] 2016-08-15 08:45
Some interesting behaviour I came across:

1. Open gmail.com in Edge with uBlock enabled
2. Find an email that contains an external link
3. Right-click -> inspect element said external link
4. Click link

Result: no crash, link opens just fine. Trying another external link in e.g. the same email, results in the same behaviour as described in the first comment of this issue.

**Comment by nikrolls** [comment] 2016-11-21 06:47
On the latest Insider Fast build and the latest version of uBlock Origin, I'm not experiencing this issue any more. Can anyone else corroborate?

**Comment by Otik** [comment] 2016-11-21 10:39
I'm on the Insider slow ring with the 1.9.17.10 build of uBlock Origin and still have the issue.

**Comment by japborst** [comment] 2016-11-23 22:36
Slow ring recently got an update. I am on the slow ring too running the latest build (win10 14965) and don't have the issue anymore. Links open just fine now, no crashes

**Comment by nikrolls** [comment] 2016-11-23 23:01
Huzzah! Thanks @japborst for the update. Looks like this will be resolved in the Creators Update then. Though it may or may not be backported to an AU cumulative update; we should probably keep this ticket open until the fix is in the wild.

**Comment by nikrolls** [comment] 2017-04-19 03:35
Closed as the Creators Update is now released.

**Closed by nikrolls** 2017-04-19 03:35 UTC
Labels: bug
