### ISSUE TITLE
Functionality to block downloads of big media doesn't work

### ISSUE THREAD

**Issue by xfix** [nikrolls/uBlock-Edge#35] opened 2016-12-12 22:35 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

[Functionality to block downloads of big media](https://github.com/nikrolls/uBlock-Edge/wiki/Per-site-switches#no-large-media-elements) doesn't work

### One or more specific URLs where the issue occurs

 http://www.wired.com/2016/01/drones-arent-just-toys-anymore

### Screenshot in which the issue can be seen

![](https://i.xfix.pw/drones.png)

Header image shouldn't appear.

### Steps for anyone to reproduce the issue

1. Enter linked website

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Edge 38.14393.0.0
- uBlock Origin version: 1.10.1

- Block media larger than: 50KB

**Comment by nikrolls** [comment] 2016-12-13 18:27
Thanks @xfix for the report! I'll take a look into it shortly.

**Comment by nikrolls** [comment] 2016-12-19 17:55
It would appear that Edge doesn't support cancelling a request in response to headers being received (it can only redirect or modify headers).

`Response error: Unexpected property name for blocking response on given event. Value must be [redirectUrl,responseHeaders]`

I'll check in with the Edge team and see if they have any thoughts.

**Comment by scottlow** [comment] 2016-12-20 20:51
Thanks for filing this! This looks like a bug on our end, so I've filed https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10284047/ to track the issue.

**Comment by nikrolls** [comment] 2016-12-21 23:48
Thanks @scottlow 😃

**Comment by nikrolls** [comment] 2017-01-13 20:40
Thanks @scottlow, I can confirm this is working in 15007! Thanks!

**Comment by xfix** [comment] 2017-03-14 23:16
It seems like KB4013429 (for build 1609) fixed this issue, which is not Insider release.

**Comment by nikrolls** [comment] 2017-04-19 03:33
Closed as this is fixed in the Creators Update.

**Closed by nikrolls** 2017-04-19 03:33 UTC
Labels: browser bug
