### ISSUE TITLE
Clicking element that doesn't load due to size restriction doesn't work

### ISSUE THREAD

**Issue by xfix** [nikrolls/uBlock-Edge#64] opened 2017-03-15 19:47 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Clicking an element with red border (that marks that the element wasn't loaded due to size limits) doesn't work, and shows an exception in developer tools.

### One or more specific URLs where the issue occurs

The page you are reading right now

### Screenshot in which the issue can be seen

![zrzut ekranu 38](https://cloud.githubusercontent.com/assets/1297598/23967621/e73c596c-09bf-11e7-8ee8-ff56a6c2dffd.png)

![zrzut ekranu 39](https://cloud.githubusercontent.com/assets/1297598/23967626/e9a2c5e2-09bf-11e7-8398-b384dffd66ca.png)

### Steps for anyone to reproduce the issue

1. Enable blocking of files bigger than 50KB in settings.
2. Refresh this page.
3. Click any of provided screenshots.
4. See nothing happening. (well, actually link is followed but image is not updated)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

Blocking of files bigger than 50KB is enabled.

- Browser/version: 38.14393.0.0
- uBlock Origin version: 1.11.2

##### Your filter lists

Default

**Comment by nikrolls** [comment] 2017-03-23 18:52
Thanks @xfix for the report, and thanks @gorhill for the fix! I'll close this issue once it comes out in the next release.

**Comment by nikrolls** [comment] 2017-03-24 04:38
Ok, looks like there's more to this. @scottlow, this might be one for your team?

The way this works is:

1. On initial load of the image, in the `onHeadersReceived` handler, the extension detects the file is oversize and requests the request be cancelled
2. When the user clicks on the blocked image to request it be loaded, uBlock (`load-large-media-interactive.js` in the foreground) removes the image's `src` attribute
3. uBlock (foreground) sends a message to the background to request that large images not be blocked for 2 seconds
4. uBlock (foreground) then assigns the `src` attribute back to the image, at which point the browser should try to reload it and uBlock (background) should let it through

However Edge is not trying to reload the image. There is no request in the Network pane, and the `onHeadersReceived` handler never fires.

**Comment by gorhill** [comment] 2017-03-24 13:53
Assuming the issue arise from using an empty string as `src`, I suppose uBO could use a `data:`- or `blob:`-based URL to work around this.

**Comment by scottlow** [comment] 2017-03-27 17:00
@nikrolls thanks for letting me know. I'll work on creating a reduced case repro this morning and will let you know what I find.

**Comment by nikrolls** [comment] 2017-03-27 20:19
Working with @scottlow around a reduced repro. Not as easy to reproduce as it would appear, so I've removed the `browser bug` label until we're sure. Thanks @gorhill for the suggestion, I'll update here with the findings.

**Comment by scottlow** [comment] 2017-03-31 20:23
Thanks @nikrolls. Any luck narrowing down the issue yet?

**Closed** 2017-04-10 20:43 UTC
