### ISSUE TITLE
Ghostery & uBlock-Edge 

### ISSUE THREAD

**Issue by affe42** [nikrolls/uBlock-Edge#50] opened 2017-01-07 10:16 UTC
### Describe the issue

It seems that you cannot run Ghostery (7.1.1.5) and uBlock (1.10.2) at the same time. One or the other always shows zero detections.

Is this Edge extensions API restriction or something else? I'm happy to bug Ghostery's devs if it's their fault. :-)

### Your settings

- Browser/version: Edge 38.14393.0.0
- uBlock Origin version: 1.10.2

**Comment by japborst** [comment] 2017-01-07 11:01
Perhaps because the other one has already blocked the request, so there's nothing left for the other one? How is the behaviour in Chrome, for example?

**Comment by affe42** [comment] 2017-01-07 11:33
On other chromium-based browsers they complement, not exclude each other. For example, with Opera, you can easily get three layers of filtering: Opera's built-in, Ghostery & uBlock Origin.

**Comment by japborst** [comment] 2017-01-07 11:35
Right. And you can confirm there is no overlap between blocked requests?

**Comment by affe42** [comment] 2017-01-07 12:06
Yes, on Opera I can selectively disable/enable either one (Ghostery / uBlock) and the other will immediately (after reload)  see the resources not filtered by the other any more. On Edge, if uBlock is active, Ghostery doesn't filter anything, even if you disable uBlock from it's settings panel.

**Comment by nikrolls** [comment] 2017-01-11 01:33
Yeah, I noticed this when Gostery came out and I tried it myself. I'm not sure what the issue is but it does appear to be browser-side and either a bug or intentional implementation detail on Microsoft's side (I haven't asked them about it to know which).

I followed these steps:
1. Install uBlock, Adblock Plus, and Ghostery. 
2. Disable all but uBlock in the browser. uBlock catches requests.
3. Enable Gostery. Ghostery catches requests, uBlock doesn't.
4. Disable uBlock, enable Adblock Plus. Adblock Plus catches requests, Ghostery doesn't.
5. Disable Adblock Plus, enable uBlock. uBlock catches requests, Ghostery doesn't.
6. Disable Ghostery, enable Adblock Plus. Adblock Plus catches requests, uBlock doesn't.

So it would appear that only the latest extension to bind to request handlers is given access to them; all previous bindings are lost.

**Comment by scottlow** [comment] 2017-01-13 01:00
This is a known issue that we have recently fixed: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10276685/

It should be fixed in the most recent Windows Insider Preview build (15007) that dropped earlier today and I'm in the process of sending the fix in for approval to back-port to Anniversary Update builds now.

**Comment by affe42** [comment] 2017-01-13 05:07
Thanks for the info!

**Comment by nikrolls** [comment] 2017-01-13 20:39
Thanks @scottlow, I can confirm this appears to be working in 15007!

**Comment by affe42** [comment] 2017-04-08 10:38
The fix has been now released with Windows 10 Creators Update. Ghostery & uBlock are now running together like they should :-)

**Closed** 2017-04-15 13:07 UTC
Labels: browser bug
