### ISSUE TITLE
got error in logger

### ISSUE THREAD

**Issue by ghajini** [nikrolls/uBlock-Edge#65] opened 2017-03-26 19:33 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
i was surfing anews article on msn, when i open logger i got this ''network error''
i don't know how to describe
### One or more specific URLs where the issue occurs

i was surfing `http://www.msn.com/en-in/news/newsindia/meat-sellers-in-up-to-go-on-indefinite-strike-from-tomorrow/ar-BByPbl2?li=AAggbRN`

### Screenshot in which the issue can be seen

![screenshot 207](https://cloud.githubusercontent.com/assets/20338483/24334506/e7bcb2b6-1288-11e7-95e0-e68ad626ddef.png)

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

default settings
- Browser/version:edge Microsoft Edge 38.14393.0.0, 
Microsoft EdgeHTML 14.14393 
- uBlock Origin version: 1.11.2

##### Your filter lists

 "Default filter lists"
##### Your custom filters (if any)
youtube.com##.ytp-ce-element-show

**Comment by nikrolls** [comment] 2017-04-16 04:00
Possibly related to #4 -- I'll look into it. Thanks!

**Comment by nikrolls** [comment] 2018-02-06 20:14
I'm closing this now as there have been no recent reports of the issue and I'm unable to reproduce it. Feel free to open it again if there is further information.

**Closed by nikrolls** 2018-02-06 20:14 UTC
