### ISSUE TITLE
filter list not updating taking memory of 1gb

### ISSUE THREAD

**Issue by ghajini** [nikrolls/uBlock-Edge#10] opened 2016-08-25 08:51 UTC
Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
### Describe the issue

manually updating filter lists not working
### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]
### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
### Steps for anyone to reproduce the issue

just click purge all caches,apply,then update ..keep running taking memory of 1gb
### Your settings

default settings
- Browser/version: edge anniversary update
- uBlock Origin version: 1.7.7
  ##### Your filter lists

Default filter lists
##### Your custom filters (if any)

none

**Comment by nikrolls** [comment] 2016-09-06 00:22
Possible duplicate of #10

**Comment by TheRyuu** [comment] 2016-09-11 02:09
> manually updating filter lists not working
> just click purge all caches,apply,then update ..keep running taking memory of 1gb

Sounds the same as #9 although the memory usage is obviously less since you're only using default lists.  If you let it sit for a little while (depending on how fast your CPU is) it should complete.

I can't remember the exact time for mine but for nearly all filters (excluding the language specific ones and a few others) on an i7-4770 it took a few minutes to complete (and 4 to 6 GB).

> Possible duplicate of #10

You mean possible duplicate of #9?

**Comment by nikrolls** [comment] 2016-11-08 18:26
@TheRyuu, I'd be interested in your feedback on whether this is still an issue now that we're handling storing filter lists in a much more efficient manner.

**Comment by nikrolls** [comment] 2016-11-08 18:26
@ghajini, I'd be interested in your feedback on whether this is still an issue now that we're handling storing filter lists in a much more efficient manner.

**Comment by nikrolls** [comment] 2016-11-21 06:45
I'm going to close this for now as I've had reports from other sources that memory issues are no longer present. It can be re-opened if necessary.

**Closed by nikrolls** 2016-11-21 06:45 UTC
