### ISSUE TITLE
in video ads

### ISSUE THREAD

**Issue by ghajini** [nikrolls/uBlock-Edge#19] opened 2016-10-09 06:45 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
1 . ublock origin in edge not working as per filter lists
2. go here 
http://www.msn.com/en-in/news/newsindia/india-never-counts-bullets-while-retaliating-rajnath-singh/ar-BBxaJT1?ocid=spartandhp

3. before playing videos , ads are displayed..
4. although same problem will not happen with chrome/firefox with ublock origin installed

### One or more specific URLs where the issue occurs

http://www.msn.com/en-in/news/newsindia/india-never-counts-bullets-while-retaliating-rajnath-singh/ar-BBxaJT1?ocid=spartandhp

### Screenshot in which the issue can be seen

![screenshot 45](https://cloud.githubusercontent.com/assets/20338483/19218509/4d5b9c12-8e19-11e6-999e-c958c9e8c312.png)

### Steps for anyone to reproduce the issue

1. go here 
http://www.msn.com/en-in/news/newsindia/india-never-counts-bullets-while-retaliating-rajnath-singh/ar-BBxaJT1?ocid=spartandhp

2. before playing videos , ads are displayed..
3. although same problem will not happen with chrome/firefox with ublock origin installed
4. probably edge not works as per ublock on chrome/firefox

### Your settings

 default settings+adblock warning removal+antiadblock killer

- Browser/version: microsoft edge
- uBlock Origin version: 1.9.11.101

##### Your filter lists

 default settings+adblock warning removal+antiadblock killer
##### Your custom filters (if any)
none

**Comment by japborst** [comment] 2016-10-09 08:41
Duplicate of #5. The Edge API that uBlock makes use of, cannot disable requests from plugins such as Adobe Flash. Flash is being used on your webpage by the player. Ads can be blocked from HTML5-based players, such as YouTube.

Disabling Flash through the Advanced Settings in Edge, results in an HTML5 player being served by your webpage. Ads should be blocked then.

**Comment by nikrolls** [comment] 2016-10-18 09:20
Thanks @japborst. Closing as this is a duplicate.

**Closed by nikrolls** 2016-10-18 09:20 UTC
