### ISSUE TITLE
Problem with websocket rule

### ISSUE THREAD

**Issue by stasjok** [nikrolls/uBlock-Edge#43] opened 2016-12-16 20:06 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

## Describe the issue
After last update (1.10.2 from store) I have issue with opening some sites. Instead of webpage loading a .htm file is downloading. In version 1.10.0-pre this websites worked (but I think in this version this rule just doesn't work, because I can't see it in web request log).
You can find similar rule in Easylist:
$websocket,domain=anime-joy.tv|boards2go.com|celebdirtylaundry.com|celebritymozo.com|...........
It happens with this domains too.

### One or more specific URLs where the issue occurs

Domains (don't know all of it or not) from rule on screenshot or from discription.

### Screenshot in which the issue can be seen

Problem I think with this rule from RUAdlist:
![untitled](https://cloud.githubusercontent.com/assets/1353637/21276426/718f1a74-c3e2-11e6-94c3-496ca3325490.png)

### Steps for anyone to reproduce the issue

1. Try to open websites from rule.

### Your settings

Defaults with with context menu option unchecked.

- Browser/version: 38.14393.0.0
- uBlock Origin version: 1.10.2

##### Your filter lists

Default filter lists + RUAdlist + Reek AntiAdblock

**Comment by raxbe** [comment] 2016-12-17 13:44
I don't have RU Adlist in use but do encounter the issue described here on [opensubtitles.org](url). The site loads fine with ABP.

**Comment by nikrolls** [comment] 2016-12-18 17:38
Sounds like it could be related to https://github.com/nikrolls/uBlock-Edge/issues/45. I'll take a look.

**Comment by nikrolls** [comment] 2016-12-19 06:25
I can confirm that this is definitely the same issue as #45; when you try to modify the response headers (which is the case in websocket rules) Edge seems to ignore all the response headers. Because one of these is Content-Type, and because without a recognised Content-Type Edge will try to save the response as a file, you get this behaviour.

@raxbe, I'm going to close this ticket because #47 has more detail around reproduction and the issue itself. Fixing #47 (which unfortunately will probably have to be done on Microsoft's side) will solve your issue as well. Until then, you could either whitelist the affected sites or disable that list, whichever you feel is most appropriate.

**Closed by nikrolls** 2016-12-19 06:25 UTC
